@echo off
echo Creating virtual environment...
python -m venv !venv
echo Activating virtual environment...
call !venv\Scripts\activate.bat
echo Installing Pip requirements...
python -m pip install --upgrade pip
echo Installing Library requirements...
cd /d "%~dp0\data"
python -m pip install -r lib.lib
echo Done!
